disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name
- line_length
- cyclomatic_complexity

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
