# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'spyfall' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'lottie-ios'
  # Pods for spyfall

end
